
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Jekyll defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

url: https://ephmeral.technology

# Theme settings / site variables
title: "Ephemeral Laboratories"
description: Web site for Ephemeral Laboratories
copyright: "Copyright ©️ 2024 H Ephemeral Laboratories"
author: Hakanai

twitter:
  username: "@HakanaiVR"
